### ISSUE TITLE
הכנה לבדיקה

### ISSUE THREAD

**Issue by tal77319** [rhaigar/students-flask-alexander#5]
בבקשה תעלה DB שכולל כל מה שצריך כדי לבדוק את רשימת הנוכחות, כך שלא צריך להריץ שום דבר לפני. עדיף שהרשימה תהיה זמינה בלי לוגין, אם צריך לוגין תרשום מה היוזר והסיסמא שצריך. בבקשה תבדוק שכל הקישורים עובדים לפני שאתה מעלה. שלח לי מייל שבדקת והכל מוכן ומה הקישור להגשה.

**Comment by rhaigar** [comment]
העלתי את ה DB ובשביל לבדוק את טופס נוכחות צריך  להוסיף לקישור /attandance
